[build]
  base    = "front"
  command = "npm install && npx expo export:web"
  publish = "front/dist"

[functions]
  directory = "server"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/index/:splat"
  status = 200
