[functions]
  directory = "server"
  node_bundler = "esbuild"

[build]
  base    = "front"
  command = "npm install && npx expo export --platform web"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
