[functions]
  directory = "server"
  node_bundler = "esbuild"

[build]
  base    = "front"
  command = "npm install && npx expo export"
  publish = "front/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
